name: Test second repo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-second-repo:
    runs-on: ubuntu-latest
    env:
      MY_ENV_FROM_YAML: "my-value"
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/checkout@v3.0.0
        name: Checkout second repository
        with:
          repository: LuisEGR/github-actions-test-second
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: ./custom_path
          ref: main

      - name: Display second repo content
        shell: bash
        run: ls -la ./custom_path

      - name: Get second repo last commit
        shell: bash
        run: |
          pwd
          ls -la .
          pushd ./custom_path
          git rev-parse HEAD
          export SECOND_GITHUB_SHA=$(git rev-parse HEAD)
          echo "SECOND_GITHUB_SHA: $SECOND_GITHUB_SHA"
          popd
          echo "SECOND_GITHUB_SHA: $SECOND_GITHUB_SHA"
      
      - name: Display env
        shell: bash
        run: env

      - name: Test
        shell: bash
        run: |
          ./cli.sh